name: JASPAR-wordcloud
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - git=2.20.1
  - pip=19.2.2
  - pyreadr=0.2.1
  - python=3.7.3
  - python-coreapi=2.3.3
  - r=3.6.0
  - setuptools=41.0.1
  - tqdm=4.35.0