name: wordclouds
channels:
  - bioconda
  - conda-forge
dependencies:
  - biopython=1.78
  - click=7.1.2
  - click-option-group=0.5.1
  - distance=0.1.3
  - fuzzywuzzy=0.18.0
  - matplotlib=3.3.3
  - nltk=3.4.4
  - nltk_data=2019.07.04
  - numpy=1.19.5
  - pandas=1.2.1
  - python=3.8.5
  - scikit-learn=0.24.1
  - tqdm=4.35.0
  - wordcloud=1.8.1
